"""Add premium_until field to User model

Revision ID: 6c4d4022efb4
Revises: b0e69ddb8124
Create Date: 2025-06-11 13:55:44.726099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4d4022efb4'
down_revision = 'b0e69ddb8124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('premium_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('premium_until')

    # ### end Alembic commands ###
