"""Add password change attempts and block status fields

Revision ID: b0e69ddb8124
Revises: 29d440c6635b
Create Date: 2025-06-11 13:22:23.672635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e69ddb8124'
down_revision = '29d440c6635b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_change_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('blocked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('blocked_until')
        batch_op.drop_column('is_blocked')
        batch_op.drop_column('password_change_attempts')

    # ### end Alembic commands ###
